name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: blaz/jenkins-action@master
      with:
        url: "http://86.58.70.49"
        user: "blaz"
        token: ${{ secrets.TOKEN }}
        job: "foobar"