name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true


    - name: trigger multiple Job
    uses: appleboy/jenkins-action@master
    with:
    url: "http://192.168.219.128:8080/"
    user: "blaz"
    token: ${{ secrets.1118aef1db59d87383ed196f250067db15 }}
    job: "job_1,job_2"
